"""Event types for the event-driven backtest engine.

The engine processes events in deterministic order:
  MarketEvent → SignalEvent → OrderEvent → FillEvent → PositionUpdateEvent → ExitEvent
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional, List, Dict
import uuid

from ..data.loader import HistoricalCandle


@dataclass
class MarketEvent:
    """A market data update event."""
    timestamp: datetime
    candle: HistoricalCandle
    event_type: str = "MARKET"

    @property
    def bar_index(self) -> int:
        return getattr(self.candle, '_bar_index', 0)


@dataclass
class SignalEvent:
    """A trading signal generated by the strategy."""
    timestamp: datetime
    direction: str  # BUY, SELL, NO_TRADE, WAIT, BLOCKED
    strategy_id: str
    raw_score: float = 0.0
    confluence: float = 0.0
    confidence: float = 0.0
    setup_grade: str = ""
    regime: str = ""
    session: str = ""
    entry_price: float = 0.0
    stop_loss: float = 0.0
    tp1: float = 0.0
    tp2: float = 0.0
    tp3: float = 0.0
    reason_codes: List[str] = field(default_factory=list)
    evidence: List[Dict] = field(default_factory=list)
    gate_results: List[Dict] = field(default_factory=list)
    event_type: str = "SIGNAL"


@dataclass
class OrderEvent:
    """An order to be executed by the simulator."""
    timestamp: datetime
    direction: str  # BUY, SELL
    size: float  # lot size
    order_type: str = "MARKET"  # MARKET, LIMIT
    stop_loss: float = 0.0
    take_profit: float = 0.0
    signal_id: str = ""
    event_type: str = "ORDER"


@dataclass
class FillEvent:
    """A simulated fill result."""
    timestamp: datetime
    direction: str
    fill_price: float
    requested_price: float
    size: float
    slippage: float = 0.0
    commission: float = 0.0
    spread_cost: float = 0.0
    fill_status: str = "FILLED"  # FILLED, PARTIAL, REJECTED
    fill_ratio: float = 1.0
    signal_id: str = ""
    event_type: str = "FILL"


@dataclass
class PositionUpdateEvent:
    """A position update (equity, unrealized PnL, etc.)."""
    timestamp: datetime
    position_id: str
    direction: str
    size: float
    entry_price: float
    current_price: float
    unrealized_pnl: float
    event_type: str = "POSITION_UPDATE"


@dataclass
class ExitEvent:
    """A position exit event."""
    timestamp: datetime
    position_id: str
    exit_price: float
    exit_reason: str  # SL, TP, TRAILING, BREAK_EVEN, TIME, STRATEGY, END
    realized_pnl: float
    commission: float = 0.0
    slippage: float = 0.0
    event_type: str = "EXIT"
