-- Reconcile audit.migration_history to on-disk migration set
-- Generated by scripts/reconcile_migrations.sh on 2026-08-27T21:18:24Z
-- Apply mode: APPLY (explicit --apply/CONFIRM)
BEGIN;
-- reversible, nullable bookkeeping columns
ALTER TABLE audit.migration_history ADD COLUMN IF NOT EXISTS checksum VARCHAR(64);
ALTER TABLE audit.migration_history ADD COLUMN IF NOT EXISTS reconciled_note TEXT;

-- capture orphans for reversible rollback before deleting
CREATE TABLE IF NOT EXISTS audit.migration_history_reconcile_backup (
  filename VARCHAR(255) NOT NULL,
  status VARCHAR(20),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);
INSERT INTO audit.migration_history_reconcile_backup (filename, status, started_at, completed_at)
SELECT filename, status, started_at, completed_at FROM audit.migration_history WHERE filename IN ('003_control_tables.sql','004_licensing_tables.sql','005_billing_tables.sql','006_referral_tables.sql','007_market_tables.sql','008_trading_tables.sql','009_research_tables.sql','010_audit_tables.sql','024_financial_integrity_webhooks_reconciliation.sql','025_referral_codes_invoice_read_models.sql','026_migration_history_reconciliation.sql','027_migration_history_catalog.sql','072_backtest_artifact_payload.sql');
DELETE FROM audit.migration_history WHERE filename IN ('003_control_tables.sql','004_licensing_tables.sql','005_billing_tables.sql','006_referral_tables.sql','007_market_tables.sql','008_trading_tables.sql','009_research_tables.sql','010_audit_tables.sql','024_financial_integrity_webhooks_reconciliation.sql','025_referral_codes_invoice_read_models.sql','026_migration_history_reconciliation.sql','027_migration_history_catalog.sql','072_backtest_artifact_payload.sql');

-- back-fill missing on-disk files
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('074_backtest_artifact_payload.sql', 'COMPLETED', now(), now(), '9c1c5fe842faa155ae7947d8cf2232ab', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('075_finance_ledger_entries.sql', 'COMPLETED', now(), now(), '1367aabef7a5e558c77397c085581d6d', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('076_market_data_metadata.sql', 'COMPLETED', now(), now(), '616caf6c7779041f77b6b1ec07649cb7', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('077_backtest_runs_owner.sql', 'COMPLETED', now(), now(), '038d98cccf01ba764e918ff8bfced28c', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('078_subscription_paused_state.sql', 'COMPLETED', now(), now(), 'ad283192f6297e0829b5a88f660bc964', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('079_payouts_idempotency.sql', 'COMPLETED', now(), now(), 'de5955a565a55a2256d0e27462f8d10f', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('080_devil_liquidity.sql', 'COMPLETED', now(), now(), '0afd1b2a8ba2a13943671a08ac71911e', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('080_signal_quality_diagnostics.sql', 'COMPLETED', now(), now(), '83cb2ad014b97dd7bc904b432511b228', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('081_market_candles_retention.sql', 'COMPLETED', now(), now(), 'e72e2f9f12ea75077fe3a5da73e59bec', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('082_elite_marnie_fib_strategy.sql', 'COMPLETED', now(), now(), '46bc4a590997f8178553f46b81230373', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('083_backfill_trade_metrics.sql', 'COMPLETED', now(), now(), '932b0fb3300cb4090d93e25f80a0ff06', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('084_add_trade_timeframe.sql', 'COMPLETED', now(), now(), 'a825989d0d7230aa98dce53258d6f165', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('085_set_plan_risk_caps.sql', 'COMPLETED', now(), now(), '34395c836487a4761c776ad8172ad720', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('086_agent_device_id_binding.sql', 'COMPLETED', now(), now(), 'eb53b2b6e8526c26f3bde301e1cdb0e4', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('087_signal_verification_columns.sql', 'COMPLETED', now(), now(), '25f893fade721f0f68c28d1ee743951b', 'back-filled by reconciliation 2026-08-27')
ON CONFLICT (filename) DO NOTHING;
COMMIT;
