#!/usr/bin/env bash
# reconcile_migrations.sh
#
# Reconciles audit.migration_history to the actual on-disk set of
# database/migrations/*.sql files.
#
# SAFETY — bookkeeping only, never re-runs or reverts any schema DDL:
#   * INSERTs a history row for every on-disk .sql file missing from history
#     (back-fill; marked with a checksum + reconciled_note).
#   * DELETEs orphan history rows whose filename no longer exists on disk.
#   * Adds two reversible, nullable columns (checksum, reconciled_note) if absent.
#   * Captures deleted orphans into audit.migration_history_reconcile_backup so
#     the operation is fully reversible via scripts/reconcile_migrations_rollback.sql.
#
# This script never renames migration files (renaming risks re-applying already
# applied schema). Duplicate numeric prefixes are a tolerated legacy issue and
# are handled by the CI uniqueness guard (scripts/check_migrations.sh).
#
# Usage:
#   ./reconcile_migrations.sh            # dry-run: prints plan + writes SQL, does NOT apply
#   ./reconcile_migrations.sh --apply    # prints plan, then applies reconcile_migrations.sql
#   CONFIRM=1 ./reconcile_migrations.sh  # same as --apply
#
set -euo pipefail

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-predictatrade}"
DB_USER="${DB_USER:-pat_admin}"
DB_PASSWORD="${DB_PASSWORD:-pat_local_dev_only}"
MIGRATIONS_DIR="${MIGRATIONS_DIR:-database/migrations}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_SQL="${OUT_SQL:-$SCRIPT_DIR/reconcile_migrations.sql}"
ROLLBACK_SQL="${ROLLBACK_SQL:-$SCRIPT_DIR/reconcile_migrations_rollback.sql}"

export PGPASSWORD="$DB_PASSWORD"
PSQL="psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -v ON_ERROR_STOP=1 -t -A"

APPLY=0
if [ "${1:-}" = "--apply" ] || [ "${CONFIRM:-}" = "1" ]; then
  APPLY=1
fi

# --- compute the two sets -----------------------------------------------------
mapfile -t DISK < <(ls "$MIGRATIONS_DIR"/*.sql 2>/dev/null | xargs -n1 basename | sort || true)
mapfile -t HIST < <(echo "SELECT filename FROM audit.migration_history;" | $PSQL 2>/dev/null | sort || true)

declare -A HSET
for h in "${HIST[@]:-}"; do [ -n "$h" ] && HSET["$h"]=1; done

missing=()
for d in "${DISK[@]:-}"; do
  [ -n "$d" ] || continue
  if [ -z "${HSET[$d]:-}" ]; then missing+=("$d"); fi
done

declare -A DSET
for d in "${DISK[@]:-}"; do [ -n "$d" ] && DSET["$d"]=1; done

orphans=()
for h in "${HIST[@]:-}"; do
  [ -n "$h" ] || continue
  if [ -z "${DSET[$h]:-}" ]; then orphans+=("$h"); fi
done

# --- print the plan -----------------------------------------------------------
echo "==================== Migration Reconciliation Plan ===================="
echo "Disk .sql files       : ${#DISK[@]}"
echo "History rows          : ${#HIST[@]}"
echo "To INSERT (missing)   : ${#missing[@]}"
echo "To DELETE (orphans)   : ${#orphans[@]}"
if [ ${#missing[@]} -gt 0 ]; then
  echo "  INSERT list (back-fill from disk):"
  printf '    + %s\n' "${missing[@]}"
fi
if [ ${#orphans[@]} -gt 0 ]; then
  echo "  DELETE list (orphan rows, captured to backup table first):"
  printf '    - %s\n' "${orphans[@]}"
fi
echo "========================================================================"

if [ ${#missing[@]} -eq 0 ] && [ ${#orphans[@]} -eq 0 ]; then
  echo "Nothing to reconcile: history already matches disk."
  exit 0
fi

# --- build reconcile_migrations.sql -------------------------------------------
orphan_in=""
if [ ${#orphans[@]} -gt 0 ]; then
  orphan_in=$(printf "'%s'," "${orphans[@]}"); orphan_in="${orphan_in%,}"
fi
missing_in=""
if [ ${#missing[@]} -gt 0 ]; then
  missing_in=$(printf "'%s'," "${missing[@]}"); missing_in="${missing_in%,}"
fi

{
  echo "-- Reconcile audit.migration_history to on-disk migration set"
  echo "-- Generated by scripts/reconcile_migrations.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "-- Apply mode: $([ $APPLY -eq 1 ] && echo 'APPLY (explicit --apply/CONFIRM)' || echo 'DRY-RUN')"
  echo "BEGIN;"
  echo "-- reversible, nullable bookkeeping columns"
  echo "ALTER TABLE audit.migration_history ADD COLUMN IF NOT EXISTS checksum VARCHAR(64);"
  echo "ALTER TABLE audit.migration_history ADD COLUMN IF NOT EXISTS reconciled_note TEXT;"
  echo ""
  echo "-- capture orphans for reversible rollback before deleting"
  if [ -n "$orphan_in" ]; then
    echo "CREATE TABLE IF NOT EXISTS audit.migration_history_reconcile_backup ("
    echo "  filename VARCHAR(255) NOT NULL,"
    echo "  status VARCHAR(20),"
    echo "  started_at TIMESTAMPTZ,"
    echo "  completed_at TIMESTAMPTZ"
    echo ");"
    echo "INSERT INTO audit.migration_history_reconcile_backup (filename, status, started_at, completed_at)"
    echo "SELECT filename, status, started_at, completed_at FROM audit.migration_history WHERE filename IN ($orphan_in);"
    echo "DELETE FROM audit.migration_history WHERE filename IN ($orphan_in);"
  fi
  echo ""
  echo "-- back-fill missing on-disk files"
  for m in "${missing[@]}"; do
    fp="$MIGRATIONS_DIR/$m"
    cs=$(md5sum "$fp" 2>/dev/null | awk '{print $1}')
    note="back-filled by reconciliation $(date -u +%Y-%m-%d)"
    echo "INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)"
    echo "VALUES ('$m', 'COMPLETED', now(), now(), '$cs', '$note')"
    echo "ON CONFLICT (filename) DO NOTHING;"
  done
  echo "COMMIT;"
} > "$OUT_SQL"

# --- build reconcile_migrations_rollback.sql ----------------------------------
{
  echo "-- Rollback for reconcile_migrations.sql"
  echo "-- Reverses the reconciliation: restores deleted orphans, removes back-filled"
  echo "-- rows, drops the backup table and the added bookkeeping columns."
  echo "BEGIN;"
  if [ -n "$orphan_in" ]; then
    echo "INSERT INTO audit.migration_history (filename, status, started_at, completed_at)"
    echo "SELECT filename, status, started_at, completed_at FROM audit.migration_history_reconcile_backup"
    echo "ON CONFLICT (filename) DO NOTHING;"
  fi
  if [ -n "$missing_in" ]; then
    echo "DELETE FROM audit.migration_history WHERE filename IN ($missing_in);"
  fi
  echo "DROP TABLE IF EXISTS audit.migration_history_reconcile_backup;"
  echo "ALTER TABLE audit.migration_history DROP COLUMN IF EXISTS checksum;"
  echo "ALTER TABLE audit.migration_history DROP COLUMN IF EXISTS reconciled_note;"
  echo "COMMIT;"
} > "$ROLLBACK_SQL"

echo "Wrote plan SQL : $OUT_SQL"
echo "Wrote rollback: $ROLLBACK_SQL"

# --- apply if requested -------------------------------------------------------
if [ $APPLY -eq 1 ]; then
  echo ""
  echo "==== APPLYING reconcile_migrations.sql against live DB ===="
  psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -v ON_ERROR_STOP=1 -f "$OUT_SQL"
  echo "==== Verification ===="
  echo "History count : $(echo "SELECT count(*) FROM audit.migration_history;" | $PSQL)"
  echo "Disk count    : $(ls "$MIGRATIONS_DIR"/*.sql | wc -l)"
else
  echo ""
  echo "==== DRY-RUN: nothing applied. Re-run with --apply (or CONFIRM=1) to apply. ===="
fi
