-- Reconcile audit.migration_history to on-disk migration set
-- Generated by scripts/reconcile_migrations.sh on 2026-09-11T20:26:29Z
-- Apply mode: APPLY (explicit --apply/CONFIRM)
BEGIN;
-- reversible, nullable bookkeeping columns
ALTER TABLE audit.migration_history ADD COLUMN IF NOT EXISTS checksum VARCHAR(64);
ALTER TABLE audit.migration_history ADD COLUMN IF NOT EXISTS reconciled_note TEXT;

-- capture orphans for reversible rollback before deleting

-- back-fill missing on-disk files
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('145_hypertable_retention_policies.sql', 'COMPLETED', now(), now(), '15932b4b8e6ce0d247e03ff4f4cdfdf9', 'back-filled by reconciliation 2026-09-11')
ON CONFLICT (filename) DO NOTHING;
INSERT INTO audit.migration_history (filename, status, started_at, completed_at, checksum, reconciled_note)
VALUES ('148_devil_liquidity_volume_weight.sql', 'COMPLETED', now(), now(), 'b284fe122d08d20b5e1f1f926eea33f8', 'back-filled by reconciliation 2026-09-11')
ON CONFLICT (filename) DO NOTHING;
COMMIT;
